# Generated by Django 5.2.8 on 2026-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
